file = open("quone.py", "ab")
# print file

# print (file.read())

file.write("\n# not code injection")

file.close()

### THE DEADLANDS ###

# not code injection
# not code injection
# not code injection

# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection
# not code injection